project 'unspayapp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'unspayapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for unspayapp
  
  pod 'Masonry'
  pod 'SVProgressHUD'
 

  target 'unspayappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'unspayappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
